@LazerServer_HostAddress = http://localhost:5048
@BeatmapHash = "473eae3bc04005fc728876b096c29fb1f5f74087046ebb2945e08612ec7c798b"

GET {{LazerServer_HostAddress}}/api/scores?rql=BeatmapHash=={{BeatmapHash}}&depth=1
Accept: application/json

###

GET {{LazerServer_HostAddress}}/api/beatmaps?rql=Hash=={{BeatmapHash}}&depth=1
Accept: application/json

###

GET {{LazerServer_HostAddress}}/api/beatmaps?rql=BeatmapSet.OnlineID==2280130
Accept: application/json

###

GET {{LazerServer_HostAddress}}/api/beatmapsets?rql=OnlineID==2280130&depth=1
Accept: application/json

###

GET {{LazerServer_HostAddress}}/api/collections?rql=Name=="love"&depth=1
Accept: application/json

###

GET {{LazerServer_HostAddress}}/files/{{BeatmapHash}}
Accept: application/octet-stream
