@HostAddress = http://localhost:5048

### Status
GET {{HostAddress}}/api/status
Accept: application/json

### APIv2: proxy - get beatmap by ID (requires configured credentials)
GET {{HostAddress}}/api/osuapi/v2/beatmaps/5288868
Accept: application/json

### APIv2: proxy - get user by ID
GET {{HostAddress}}/api/osuapi/v2/users/95915
Accept: application/json

### APIv2: proxy - download replay (requires configured credentials)
GET {{HostAddress}}/api/osuapi/v2/scores/mania/635785967/download
Accept: application/octet-stream

### APIv2: proxy - get rankings (requires configured credentials)
GET {{HostAddress}}/api/osuapi/v2/rankings/osu/performance?page=1
Accept: application/json
